[server]
# Increase max upload size to 1GB (1024MB)
maxUploadSize = 1024

# Increase max message size for large files
maxMessageSize = 1024

# Increase timeouts for large file uploads
enableCORS = false
enableXsrfProtection = false

# Enable file watcher for development
fileWatcherType = "auto"

# Port configuration
port = 8501

# Increase connection timeout
headless = false

[browser]
# Don't automatically open browser
gatherUsageStats = false

[theme]
# Optional: Set theme colors
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Show error details
showErrorDetails = true

[runner]
# Increase memory limit for large file processing
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Set logging level
level = "info"
