// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: v1/analytics.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetTeacherDashboard_FullMethodName = "/v1.AnalyticsService/GetTeacherDashboard"
	AnalyticsService_GetTeacherStudents_FullMethodName  = "/v1.AnalyticsService/GetTeacherStudents"
	AnalyticsService_GetTeacherExams_FullMethodName     = "/v1.AnalyticsService/GetTeacherExams"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// Get teacher dashboard overview with stats and trends
	GetTeacherDashboard(ctx context.Context, in *GetTeacherDashboardRequest, opts ...grpc.CallOption) (*GetTeacherDashboardResponse, error)
	// Get list of students enrolled in teacher's courses
	GetTeacherStudents(ctx context.Context, in *GetTeacherStudentsRequest, opts ...grpc.CallOption) (*GetTeacherStudentsResponse, error)
	// Get list of exams created by teacher
	GetTeacherExams(ctx context.Context, in *GetTeacherExamsRequest, opts ...grpc.CallOption) (*GetTeacherExamsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetTeacherDashboard(ctx context.Context, in *GetTeacherDashboardRequest, opts ...grpc.CallOption) (*GetTeacherDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeacherDashboardResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTeacherDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTeacherStudents(ctx context.Context, in *GetTeacherStudentsRequest, opts ...grpc.CallOption) (*GetTeacherStudentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeacherStudentsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTeacherStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTeacherExams(ctx context.Context, in *GetTeacherExamsRequest, opts ...grpc.CallOption) (*GetTeacherExamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeacherExamsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTeacherExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	// Get teacher dashboard overview with stats and trends
	GetTeacherDashboard(context.Context, *GetTeacherDashboardRequest) (*GetTeacherDashboardResponse, error)
	// Get list of students enrolled in teacher's courses
	GetTeacherStudents(context.Context, *GetTeacherStudentsRequest) (*GetTeacherStudentsResponse, error)
	// Get list of exams created by teacher
	GetTeacherExams(context.Context, *GetTeacherExamsRequest) (*GetTeacherExamsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetTeacherDashboard(context.Context, *GetTeacherDashboardRequest) (*GetTeacherDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeacherDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTeacherStudents(context.Context, *GetTeacherStudentsRequest) (*GetTeacherStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeacherStudents not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTeacherExams(context.Context, *GetTeacherExamsRequest) (*GetTeacherExamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeacherExams not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetTeacherDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTeacherDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTeacherDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTeacherDashboard(ctx, req.(*GetTeacherDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTeacherStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTeacherStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTeacherStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTeacherStudents(ctx, req.(*GetTeacherStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTeacherExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherExamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTeacherExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTeacherExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTeacherExams(ctx, req.(*GetTeacherExamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeacherDashboard",
			Handler:    _AnalyticsService_GetTeacherDashboard_Handler,
		},
		{
			MethodName: "GetTeacherStudents",
			Handler:    _AnalyticsService_GetTeacherStudents_Handler,
		},
		{
			MethodName: "GetTeacherExams",
			Handler:    _AnalyticsService_GetTeacherExams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/analytics.proto",
}
