# Dependabot Configuration for NyNus Exam Bank System
# Automated dependency updates and security monitoring

version: 2
updates:
  # Frontend (Next.js) Dependencies
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    reviewers:
      - "nynus-dev-team"
    assignees:
      - "nynus-dev-team"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Security updates - always create PR
    versioning-strategy: increase
    # Group updates by type
    groups:
      # Critical security updates - separate PRs
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      # React ecosystem
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
          - "next*"
          - "eslint-config-next"
        update-types:
          - "minor"
          - "patch"
      # UI libraries
      ui-libraries:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwindcss*"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
      # Development tools
      dev-tools:
        patterns:
          - "eslint*"
          - "typescript"
          - "@types/*"
          - "prettier"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages
    ignore:
      # Major version updates require manual review
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "zod"
        update-types: ["version-update:semver-major"]
      # Deprecated packages - will be replaced manually
      - dependency-name: "@types/bcryptjs"
      - dependency-name: "@types/sharp"
      - dependency-name: "critters"

  # Backend (Go) Dependencies
  - package-ecosystem: "gomod"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    reviewers:
      - "nynus-dev-team"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Security updates
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      # gRPC ecosystem
      grpc-ecosystem:
        patterns:
          - "google.golang.org/grpc*"
          - "google.golang.org/protobuf*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci-cd"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

