# OpenSearch Configuration for Vietnamese Search
# Cấu hình OpenSearch cho tìm kiếm tiếng Việt với education domain optimization

cluster.name: exam-bank-opensearch
node.name: exam-bank-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings for single node
discovery.type: single-node
# Note: cluster.initial_master_nodes is not allowed with single-node discovery

# Security settings (disabled for development)
plugins.security.disabled: true

# Performance settings
bootstrap.memory_lock: true
indices.query.bool.max_clause_count: 10000

# Logging
logger.level: INFO
logger.org.opensearch.discovery: DEBUG

# Cluster settings
cluster.routing.allocation.disk.threshold_enabled: false

# NOTE: Index-level settings (analysis, filters, etc.) have been moved to index templates
# These will be applied when indices are created via the index template in index-templates/
