// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/v1/question_service.proto

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Import Questions Messages
type ImportQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvDataBase64 string                 `protobuf:"bytes,1,opt,name=csv_data_base64,json=csvDataBase64,proto3" json:"csv_data_base64,omitempty"` // Base64 encoded CSV data
	UpsertMode    bool                   `protobuf:"varint,2,opt,name=upsert_mode,json=upsertMode,proto3" json:"upsert_mode,omitempty"`           // If true, update existing questions by ID
	Creator       string                 `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`                                    // User creating/importing the questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportQuestionsRequest) Reset() {
	*x = ImportQuestionsRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportQuestionsRequest) ProtoMessage() {}

func (x *ImportQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ImportQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImportQuestionsRequest) GetCsvDataBase64() string {
	if x != nil {
		return x.CsvDataBase64
	}
	return ""
}

func (x *ImportQuestionsRequest) GetUpsertMode() bool {
	if x != nil {
		return x.UpsertMode
	}
	return false
}

func (x *ImportQuestionsRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type ImportQuestionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalProcessed int32                  `protobuf:"varint,1,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	CreatedCount   int32                  `protobuf:"varint,2,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	UpdatedCount   int32                  `protobuf:"varint,3,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	ErrorCount     int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Errors         []*ImportError         `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportQuestionsResponse) Reset() {
	*x = ImportQuestionsResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportQuestionsResponse) ProtoMessage() {}

func (x *ImportQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ImportQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{1}
}

func (x *ImportQuestionsResponse) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *ImportQuestionsResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *ImportQuestionsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *ImportQuestionsResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ImportQuestionsResponse) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ImportQuestionsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNumber     int32                  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	FieldName     string                 `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RowData       string                 `protobuf:"bytes,4,opt,name=row_data,json=rowData,proto3" json:"row_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{2}
}

func (x *ImportError) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *ImportError) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ImportError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ImportError) GetRowData() string {
	if x != nil {
		return x.RowData
	}
	return ""
}

// Question Messages
type Question struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RawContent     string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Subcount       string                 `protobuf:"bytes,4,opt,name=subcount,proto3" json:"subcount,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // MC, TF, SA, ES, MA
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Answers        string                 `protobuf:"bytes,7,opt,name=answers,proto3" json:"answers,omitempty"`                                  // JSON string
	CorrectAnswer  string                 `protobuf:"bytes,8,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"` // JSON string
	Solution       string                 `protobuf:"bytes,9,opt,name=solution,proto3" json:"solution,omitempty"`
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	UsageCount     int32                  `protobuf:"varint,11,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	Creator        string                 `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	Status         string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"` // ACTIVE, PENDING, INACTIVE, ARCHIVED
	Feedback       int32                  `protobuf:"varint,14,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Difficulty     string                 `protobuf:"bytes,15,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // EASY, MEDIUM, HARD
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp   `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	QuestionCodeId string                 `protobuf:"bytes,18,opt,name=question_code_id,json=questionCodeId,proto3" json:"question_code_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Question) GetSubcount() string {
	if x != nil {
		return x.Subcount
	}
	return ""
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Question) GetAnswers() string {
	if x != nil {
		return x.Answers
	}
	return ""
}

func (x *Question) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *Question) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *Question) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Question) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *Question) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Question) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Question) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Question) GetQuestionCodeId() string {
	if x != nil {
		return x.QuestionCodeId
	}
	return ""
}

// Create Question Messages
type CreateQuestionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawContent     string                 `protobuf:"bytes,1,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty     string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Source         string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Solution       string                 `protobuf:"bytes,6,opt,name=solution,proto3" json:"solution,omitempty"`
	Creator        string                 `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	QuestionCodeId string                 `protobuf:"bytes,8,opt,name=question_code_id,json=questionCodeId,proto3" json:"question_code_id,omitempty"`
	Answers        string                 `protobuf:"bytes,9,opt,name=answers,proto3" json:"answers,omitempty"`
	CorrectAnswer  string                 `protobuf:"bytes,10,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Tags           []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQuestionRequest) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *CreateQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateQuestionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateQuestionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateQuestionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *CreateQuestionRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *CreateQuestionRequest) GetQuestionCodeId() string {
	if x != nil {
		return x.QuestionCodeId
	}
	return ""
}

func (x *CreateQuestionRequest) GetAnswers() string {
	if x != nil {
		return x.Answers
	}
	return ""
}

func (x *CreateQuestionRequest) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *CreateQuestionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *CreateQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get Question Messages
type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

// Get Questions by Code Messages
type GetQuestionsByCodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionCodeId string                 `protobuf:"bytes,1,opt,name=question_code_id,json=questionCodeId,proto3" json:"question_code_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuestionsByCodeRequest) Reset() {
	*x = GetQuestionsByCodeRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsByCodeRequest) ProtoMessage() {}

func (x *GetQuestionsByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionsByCodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuestionsByCodeRequest) GetQuestionCodeId() string {
	if x != nil {
		return x.QuestionCodeId
	}
	return ""
}

type GetQuestionsByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsByCodeResponse) Reset() {
	*x = GetQuestionsByCodeResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsByCodeResponse) ProtoMessage() {}

func (x *GetQuestionsByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsByCodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuestionsByCodeResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetQuestionsByCodeResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Update Question Messages
type UpdateQuestionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RawContent     string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty     string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Solution       string                 `protobuf:"bytes,7,opt,name=solution,proto3" json:"solution,omitempty"`
	QuestionCodeId string                 `protobuf:"bytes,8,opt,name=question_code_id,json=questionCodeId,proto3" json:"question_code_id,omitempty"`
	Answers        string                 `protobuf:"bytes,9,opt,name=answers,proto3" json:"answers,omitempty"`
	CorrectAnswer  string                 `protobuf:"bytes,10,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Tags           []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuestionRequest) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *UpdateQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateQuestionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateQuestionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateQuestionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *UpdateQuestionRequest) GetQuestionCodeId() string {
	if x != nil {
		return x.QuestionCodeId
	}
	return ""
}

func (x *UpdateQuestionRequest) GetAnswers() string {
	if x != nil {
		return x.Answers
	}
	return ""
}

func (x *UpdateQuestionRequest) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *UpdateQuestionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *UpdateQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Delete Question Messages
type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_question_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_question_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_v1_question_service_proto protoreflect.FileDescriptor

const file_pkg_proto_v1_question_service_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/v1/question_service.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n" +
	"\x16ImportQuestionsRequest\x12&\n" +
	"\x0fcsv_data_base64\x18\x01 \x01(\tR\rcsvDataBase64\x12\x1f\n" +
	"\vupsert_mode\x18\x02 \x01(\bR\n" +
	"upsertMode\x12\x18\n" +
	"\acreator\x18\x03 \x01(\tR\acreator\"\xf0\x01\n" +
	"\x17ImportQuestionsResponse\x12'\n" +
	"\x0ftotal_processed\x18\x01 \x01(\x05R\x0etotalProcessed\x12#\n" +
	"\rcreated_count\x18\x02 \x01(\x05R\fcreatedCount\x12#\n" +
	"\rupdated_count\x18\x03 \x01(\x05R\fupdatedCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\x12'\n" +
	"\x06errors\x18\x05 \x03(\v2\x0f.v1.ImportErrorR\x06errors\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"\x8b\x01\n" +
	"\vImportError\x12\x1d\n" +
	"\n" +
	"row_number\x18\x01 \x01(\x05R\trowNumber\x12\x1d\n" +
	"\n" +
	"field_name\x18\x02 \x01(\tR\tfieldName\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\brow_data\x18\x04 \x01(\tR\arowData\"\xbd\x04\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bsubcount\x18\x04 \x01(\tR\bsubcount\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\aanswers\x18\a \x01(\tR\aanswers\x12%\n" +
	"\x0ecorrect_answer\x18\b \x01(\tR\rcorrectAnswer\x12\x1a\n" +
	"\bsolution\x18\t \x01(\tR\bsolution\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1f\n" +
	"\vusage_count\x18\v \x01(\x05R\n" +
	"usageCount\x12\x18\n" +
	"\acreator\x18\f \x01(\tR\acreator\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1a\n" +
	"\bfeedback\x18\x0e \x01(\x05R\bfeedback\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x0f \x01(\tR\n" +
	"difficulty\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\x10question_code_id\x18\x12 \x01(\tR\x0equestionCodeId\"\xd3\x02\n" +
	"\x15CreateQuestionRequest\x12\x1f\n" +
	"\vraw_content\x18\x01 \x01(\tR\n" +
	"rawContent\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1a\n" +
	"\bsolution\x18\x06 \x01(\tR\bsolution\x12\x18\n" +
	"\acreator\x18\a \x01(\tR\acreator\x12(\n" +
	"\x10question_code_id\x18\b \x01(\tR\x0equestionCodeId\x12\x18\n" +
	"\aanswers\x18\t \x01(\tR\aanswers\x12%\n" +
	"\x0ecorrect_answer\x18\n" +
	" \x01(\tR\rcorrectAnswer\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\"\\\n" +
	"\x16CreateQuestionResponse\x12(\n" +
	"\bquestion\x18\x01 \x01(\v2\f.v1.QuestionR\bquestion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x13GetQuestionResponse\x12(\n" +
	"\bquestion\x18\x01 \x01(\v2\f.v1.QuestionR\bquestion\"E\n" +
	"\x19GetQuestionsByCodeRequest\x12(\n" +
	"\x10question_code_id\x18\x01 \x01(\tR\x0equestionCodeId\"i\n" +
	"\x1aGetQuestionsByCodeResponse\x12*\n" +
	"\tquestions\x18\x01 \x03(\v2\f.v1.QuestionR\tquestions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xc9\x02\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1a\n" +
	"\bsolution\x18\a \x01(\tR\bsolution\x12(\n" +
	"\x10question_code_id\x18\b \x01(\tR\x0equestionCodeId\x12\x18\n" +
	"\aanswers\x18\t \x01(\tR\aanswers\x12%\n" +
	"\x0ecorrect_answer\x18\n" +
	" \x01(\tR\rcorrectAnswer\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\"\\\n" +
	"\x16UpdateQuestionResponse\x12(\n" +
	"\bquestion\x18\x01 \x01(\v2\f.v1.QuestionR\bquestion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15DeleteQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcd\x03\n" +
	"\x0fQuestionService\x12J\n" +
	"\x0fImportQuestions\x12\x1a.v1.ImportQuestionsRequest\x1a\x1b.v1.ImportQuestionsResponse\x12G\n" +
	"\x0eCreateQuestion\x12\x19.v1.CreateQuestionRequest\x1a\x1a.v1.CreateQuestionResponse\x12>\n" +
	"\vGetQuestion\x12\x16.v1.GetQuestionRequest\x1a\x17.v1.GetQuestionResponse\x12S\n" +
	"\x12GetQuestionsByCode\x12\x1d.v1.GetQuestionsByCodeRequest\x1a\x1e.v1.GetQuestionsByCodeResponse\x12G\n" +
	"\x0eUpdateQuestion\x12\x19.v1.UpdateQuestionRequest\x1a\x1a.v1.UpdateQuestionResponse\x12G\n" +
	"\x0eDeleteQuestion\x12\x19.v1.DeleteQuestionRequest\x1a\x1a.v1.DeleteQuestionResponseBAZ?github.com/AnhPhan49/exam-bank-system/apps/backend/pkg/proto/v1b\x06proto3"

var (
	file_pkg_proto_v1_question_service_proto_rawDescOnce sync.Once
	file_pkg_proto_v1_question_service_proto_rawDescData []byte
)

func file_pkg_proto_v1_question_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_v1_question_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v1_question_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_question_service_proto_rawDesc), len(file_pkg_proto_v1_question_service_proto_rawDesc)))
	})
	return file_pkg_proto_v1_question_service_proto_rawDescData
}

var file_pkg_proto_v1_question_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_proto_v1_question_service_proto_goTypes = []any{
	(*ImportQuestionsRequest)(nil),     // 0: v1.ImportQuestionsRequest
	(*ImportQuestionsResponse)(nil),    // 1: v1.ImportQuestionsResponse
	(*ImportError)(nil),                // 2: v1.ImportError
	(*Question)(nil),                   // 3: v1.Question
	(*CreateQuestionRequest)(nil),      // 4: v1.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),     // 5: v1.CreateQuestionResponse
	(*GetQuestionRequest)(nil),         // 6: v1.GetQuestionRequest
	(*GetQuestionResponse)(nil),        // 7: v1.GetQuestionResponse
	(*GetQuestionsByCodeRequest)(nil),  // 8: v1.GetQuestionsByCodeRequest
	(*GetQuestionsByCodeResponse)(nil), // 9: v1.GetQuestionsByCodeResponse
	(*UpdateQuestionRequest)(nil),      // 10: v1.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),     // 11: v1.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),      // 12: v1.DeleteQuestionRequest
	(*DeleteQuestionResponse)(nil),     // 13: v1.DeleteQuestionResponse
	(*timestamp.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_pkg_proto_v1_question_service_proto_depIdxs = []int32{
	2,  // 0: v1.ImportQuestionsResponse.errors:type_name -> v1.ImportError
	14, // 1: v1.Question.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: v1.Question.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: v1.CreateQuestionResponse.question:type_name -> v1.Question
	3,  // 4: v1.GetQuestionResponse.question:type_name -> v1.Question
	3,  // 5: v1.GetQuestionsByCodeResponse.questions:type_name -> v1.Question
	3,  // 6: v1.UpdateQuestionResponse.question:type_name -> v1.Question
	0,  // 7: v1.QuestionService.ImportQuestions:input_type -> v1.ImportQuestionsRequest
	4,  // 8: v1.QuestionService.CreateQuestion:input_type -> v1.CreateQuestionRequest
	6,  // 9: v1.QuestionService.GetQuestion:input_type -> v1.GetQuestionRequest
	8,  // 10: v1.QuestionService.GetQuestionsByCode:input_type -> v1.GetQuestionsByCodeRequest
	10, // 11: v1.QuestionService.UpdateQuestion:input_type -> v1.UpdateQuestionRequest
	12, // 12: v1.QuestionService.DeleteQuestion:input_type -> v1.DeleteQuestionRequest
	1,  // 13: v1.QuestionService.ImportQuestions:output_type -> v1.ImportQuestionsResponse
	5,  // 14: v1.QuestionService.CreateQuestion:output_type -> v1.CreateQuestionResponse
	7,  // 15: v1.QuestionService.GetQuestion:output_type -> v1.GetQuestionResponse
	9,  // 16: v1.QuestionService.GetQuestionsByCode:output_type -> v1.GetQuestionsByCodeResponse
	11, // 17: v1.QuestionService.UpdateQuestion:output_type -> v1.UpdateQuestionResponse
	13, // 18: v1.QuestionService.DeleteQuestion:output_type -> v1.DeleteQuestionResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_v1_question_service_proto_init() }
func file_pkg_proto_v1_question_service_proto_init() {
	if File_pkg_proto_v1_question_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_question_service_proto_rawDesc), len(file_pkg_proto_v1_question_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v1_question_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v1_question_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_v1_question_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_v1_question_service_proto = out.File
	file_pkg_proto_v1_question_service_proto_goTypes = nil
	file_pkg_proto_v1_question_service_proto_depIdxs = nil
}
