name: mobile
description: NyNus Exam Bank Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Routing
  go_router: ^13.0.0
  
  # Network
  grpc: ^3.2.4
  protobuf: ^3.1.0
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Connectivity & Sync
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  
  # Utils
  dartz: ^0.10.1
  intl: ^0.18.1
  logger: ^2.0.2+1
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Biometric Auth
  local_auth: ^2.1.8
  
  # LaTeX & Math
  flutter_math_fork: ^0.7.1
  
  # Share
  share_plus: ^7.2.1
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_pdfview: ^1.3.2
  
  # Downloads
  dio: ^5.4.0
  path: ^1.8.3
  
  # Markdown & URL
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.2
  
  # Image Picker
  image_picker: ^1.0.5
  
  # Charts (optional - for statistics)
  fl_chart: ^0.65.0
  
  # Firebase (optional - for analytics)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+9
  firebase_remote_config: ^4.3.9
  firebase_messaging: ^14.7.9
  
  # Local Notifications
  flutter_local_notifications: ^16.3.2
  
  # Device Info
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.3
  bloc_test: ^9.1.5
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

