name: Flutter Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/mobile/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/mobile/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Get dependencies
        working-directory: apps/mobile
        run: flutter pub get
      
      - name: Run code generation
        working-directory: apps/mobile
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Analyze code
        working-directory: apps/mobile
        run: flutter analyze
      
      - name: Run tests
        working-directory: apps/mobile
        run: flutter test --coverage --reporter expanded
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: apps/mobile/coverage/lcov.info
          flags: flutter
          name: flutter-coverage

