version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: exam_bank_db
      POSTGRES_USER: exam_bank_user
      POSTGRES_PASSWORD: exam_bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../../apps/backend
      dockerfile: ../../tools/docker/Dockerfile.backend
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=exam_bank_user
      - DB_PASSWORD=exam_bank_password
      - DB_NAME=exam_bank_db

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: ../../tools/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
